- name: Install Helm, Krew & ouctl for deploying OpenUnison Authentication Portal
  hosts: all
  tasks:

    - name: Install Helm
      include_role: 
        name: gantsign.helm

    - name: Install kubectl
      include_role:
        name: andrewrothstein.kubectl

    - name: Install Krew
      include_role:
        name: pekk4.kubectl_krew
    
    - name: Install ouctl
      shell: "kubectl krew install --manifest-url=https://nexus.tremolo.io/repository/ouctl/ouctl.yaml"

    - name: Add bash autocompletion for kubectl and Krew to PATH
      lineinfile:
        dest: .bashrc
        line: '{{ item }}'
      with_items:
        - source <(kubectl completion bash)
        - alias k=kubectl
        - complete -o default -F __start_kubectl k
        - export PATH="${PATH}:${HOME}/.krew/bin"
